[versions]
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotest = "6.1.3"
mockk = "1.14.9"
ktlint-plugin = "14.0.1"
ktlint = "1.0.1"
aws-sdk = "1.6.17"
spring-boot = "3.3.2"
spring-dependency-management = "1.1.6"

[libraries]
# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Testing
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# AWS
aws-s3 = { module = "aws.sdk.kotlin:s3", version.ref = "aws-sdk" }

# Spring Boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }